//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::category::Entity as Category;
pub use super::group::Entity as Group;
pub use super::schedule::Entity as Schedule;
pub use super::schedule_group::Entity as ScheduleGroup;
pub use super::task::Entity as Task;
pub use super::user::Entity as User;
pub use super::user_group::Entity as UserGroup;
